version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${DATABASE_DATABASE}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - indefinite-studies-api-volume:/var/lib/mysql
volumes:
  indefinite-studies-api-volume:
