version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - liquibase
  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./migrations:/liquibase/changelog
    command: [
        "liquibase",
        "--username=${DATABASE_USER}",
        "--password=${DATABASE_PASSWORD}",
        "--changeLogFile=changelog/db.changelog-root.xml",
        "--url=${DATABASE_URL}",
        "update"
    ]
networks:
  default:
    external: true
    name: indefinite-studies-environment